name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: check out repository code
        uses: actions/checkout@v2
      -
        name: dockerhub login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      -
        name: buildx images
        run: docker buildx create --name mybuilder && \
             docker buildx ls && \
             docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t 18390753385a/flask-redis:latest .
            
      
