name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -  
        name: docker image build
        run: docker build -t 18390753385a/flask-redis .
      -
        name: list docker image 
        run: docker image ls
      -
        name: dockerhub login
        run: docker login -u ${{secrets.DOCKERHUB.USERNAME}} -p ${{secrets.DOCKERHUB.PASSWORD}}
      -
        name: push to dockerhub
        run: docker image push 18390753385a/flask-redis
        
